### ISSUE TITLE
iPad mini/pro UserAgent has changed

### ISSUE THREAD

**Issue by charlesr1971** [GiancarloGomez/ColdFusion-MobileDetect#2]
**iPad mini/pro** UserAgent has changed to:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15`

The **MacOSX** UserAgent is:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15`

The **iPad** and **MacOSX** UserAgent strings are almost identical.

Basically, the 'iPad' string has been removed from the UserAgent. 
The **iPad** UserAgent used to be:

`Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
`

Which made it easy to detect.

Currently, it is only possible to detect an **iPad** by looking at its on touch capabilities. In JavaScript:

`var isIPad = /Macintosh/.test(navigator.userAgent) && 'ontouchend' in document;`

Or for backward compatibility:

`var isIPad = /Macintosh|iPad/.test(navigator.userAgent) && 'ontouchend' in document;`

But, I am not sure how this is possible using a Server Side language like CFML?

**Comment by GiancarloGomez** [comment]
@charlesr1971 this was actually the cause of iPadOS not because it is a mini or pro model. iPadOS shipped with a desktop-class browser. You are correct that the only way to validate now is to do it with an additional client side check. If you want to push it back to the server side object ( if you are saving to session ), is to run the check once on the client and send it back to the server via an Ajax request, or save it to a cookie, like this you don't have to keep running the check on the client side on each request.

**Comment by charlesr1971** [comment]
@GiancarloGomez The problem with your fix is that the value isn't available the first time the browser opens. And I use the detection flag to fix certain layout issues, which means the layout will be incorrect the first time the user hits the website. First impressions count, so this is not ideal. But as you say I am not sure there is anything else we can do about this. 

Its nice to know that Apple thinks about the developer community, when upgrading its iOS. I mean how difficult would it be for Apple to keep the word iPad in the USERAGENT string?????

**Comment by GiancarloGomez** [comment]
@charlesr1971 I totally understand and I had used it like that previously but honestly the change is because the browser on the device is meant to give and gives the user a desktop experience. You should be able to fix those layout issues using CSS and media queries unless you are serving a completely different layout from the server side ( also something I had done in the past with projects that needed a quick mobile layout and due to budget limitations they could not update their old designs into a full responsive layout ) .... I feel your pain.
